version: '3.9'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rixit-api
    env_file:
      - ../.env.example
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - rixit-net
  postgres:
    image: postgres:15-alpine
    container_name: rixit-postgres
    environment:
      POSTGRES_USER: rixit
      POSTGRES_PASSWORD: rixit
      POSTGRES_DB: rixit
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rixit-net
  redis:
    image: redis:7-alpine
    container_name: rixit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rixit-net

volumes:
  postgres-data:
  redis-data:

networks:
  rixit-net: 